name: Build Eleventy

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./publish
          github_token: ${{ secrets.GITHUB_TOKEN }}
